#!/bin/env python

import random
import math

rng = random.SystemRandom()

def readWords():
    with open('words') as file:
        return [line.strip() for line in file]

words = readWords()

def passphrase(desiredBits = 79):
    numWords = len(words)
    count = int(math.ceil(desiredBits/math.log(numWords,2)))
    passWords = [words[rng.randrange(numWords)] for i in range(count)]
    return " ".join(passWords)

for i in range(20):
    print passphrase()
